---
title: "🔬 GGIR mMarch Test on One ActiGraph File"
output: html_notebook
---
Input files need to be exported CSVs.
Set the input and output directories and timezone here:
```{r}
rawdatadir="~/Documents/cmi/actigraphy"
datadir="~/Documents/cmi/actigraphy_converted"
outputdir="~/Documents/cmi/actigraphy_outputs"
timezone="America/New_York"
```

requires:
- GGIR
- zoo

```{r}
library(GGIR)
g.shell.GGIR(
  studyname="HealthyBrainNetwork",
  datadir=datadir,
  outputdir=outputdir,
  mode=c(1,2,3,4),
  idloc=1,
  print.filename=TRUE,
  storefolderstructure=FALSE,
  desiredtz=timezone,
  do.enmo=TRUE,
  do.anglez=TRUE,
  do.hfen=FALSE,
  windowsizes=c(5,900,3600),
  do.cal=TRUE,
  chunksize=1,
  printsummary=TRUE,
  strategy=1,
  hrs.del.start=0,
  hrs.del.end=0,
  maxdur=15,
  includedaycrit=16,
  winhr=c(5,10),
  epochvalues2csv=TRUE,
  L2M5window=c(0,24),
  M5L5res=10,
  qlevels=c(c(1380/1440),c(1410/1440)),
  qwindow=c(0,24),
  ilevels=c(seq(0,400,by=50),8000),
  mvpathreshold=c(125),
  do.imp=TRUE,
  timethreshold=c(5),
  anglethreshold=5,
  ignorenonwear=TRUE,
  excludefirstlast=FALSE,
  includenightcrit=16,
  def.noc.sleep=c(1),
  outliers.only=FALSE,
  relyonsleeplog=FALSE,
  sleeplogidnum=FALSE,
  do.visual=TRUE,
  criterror=0,
  nnights=14,
  threshold.lig=c(30,40,50),
  threshold.mod=c(100,120,125),
  threshold.vig=c(400,500),
  boutcriter=0.8,
  boutcriter.in=0.9,
  boutcriter.lig=0.8,
  boutcriter.mvpa=0.8,
  boutdur.in=c(10,20,30),
  boutdur.lig=c(1,5, 10),
  boutdur.mvpa=c(1,5,10),
  timewindow=c("WW"),
  do.report=c(2,4,5),
  visualreport=TRUE,
  dofirstpage=TRUE,
  viewingwindow=1
)
```

